### ISSUE TITLE
Gallery.php - move create animation button

### ISSUE THREAD

**Issue by jacksonmeyn** [Aythir/JCJS.ComputingProject2018_S2#74]
Create animation feature works great, but button is at bottom of page. Should be a top menu item instead

**Comment by posmarket** [comment]
You mean in the top menu/hamburger menu?

**Comment by jacksonmeyn** [comment]
Yes. Looks like the existing div was designed to be a modal, but it triggers a modal with instructions anyway, so it could just be a top menu item. Does that make sense?

**Comment by posmarket** [comment]
Could be difficult to implement it that was since the button needs to change depending on the state. I mean once the animation button is clicked then it needs to remove itself and then add 3 more buttons to the page (merge, reset and cancel). If the cancel button is clicked then the page needs to revert back to normal.

**Comment by posmarket** [comment]
Done as discussed in the meeting (using bottom navbar)
